### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by wouterverduin** [jakubburkiewicz/node-red-contrib-ollama#1]
Hi @jakubburkiewicz great work on this implementation for Ollama in NR!

However, i run Ollama on another device than my NR. Is it possible to add a config to use an external Ollama instance?

Thanks in advance!

**Comment by jakubburkiewicz** [comment]
Hi @wouterverduin

I might be wrong, but that sounds like adding functionality beyond the scope of the ollama.js library, which I want to avoid in this project.

Try to describe how you envision the configuration step by step

I will try to assess whether it fits within this project or should rather be implemented as a separate NR plugin.

**Comment by jakubburkiewicz** [comment]
@wouterverduin 

You haven't responded, so I checked the issue myself.

In my opinion, you should run Ollama with a configured server (https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-configure-ollama-server), and then in NR use a standard `http request` node to send request to external Ollama server.

It turns out, then, that there is no need to add a new feature to this project.

**Comment by jakubburkiewicz** [comment]
Hi @tedstriker 
That's a very good idea to add support for the host parameter :)
You can make a pull request with this change or wait until next Monday.

**Comment by jakubburkiewicz** [comment]
@wouterverduin , @tedstriker 
In version 0.1.7, you will find host selection support.

**Comment by wouterverduin** [comment]
@jakubburkiewicz 

Absolute hero! Great work!

**Comment by tedstriker** [comment]
Sweet, thank you :)
