### ISSUE TITLE
XMLHttpRequest

### ISSUE THREAD

**Issue by chrisn-au** [jakubburkiewicz/node-red-contrib-ollama#2]
Hi, 

Great idea for a module thxs

I am getting a [error] [ollama-chat:Chat] ReferenceError: XMLHttpRequest is not defined error when trying to invoke a chat

Environment  - In a docker instance

```
28 May 04:35:11 - [info] Node-RED version: v3.1.9
28 May 04:35:11 - [info] Node.js  version: v16.20.2
28 May 04:35:11 - [info] Linux 5.15.49-linuxkit-pr arm64 LE
28 May 04:35:11 - [info] Loading palette nodes
28 May 04:35:11 - [info] Settings file  : /data/settings.js
28 May 04:35:11 - [info] Context store  : 'default' [module=memory]
28 May 04:35:11 - [info] User directory : /data
28 May 04:35:11 - [warn] Projects disabled : editorTheme.projects.enabled=false
28 May 04:35:11 - [info] Flows file     : /data/flows.json
28 May 04:35:11 - [warn] 
```
A trivial chat invocation

```
msg.payload = {
    "host": "host.docker.internal:11434",
    "model": "llama3",
    "messages": [
            {
                "role": "user",
                "content": "What is your real name?"
            }
    ],
    "format" : "",
    "stream" : false,
    "keep_alive" : 10000,
    "options" : ""
}
```

Thxs

**Comment by chrisn-au** [comment]
Nice, thx appreciate the efforts

**Comment by jakubburkiewicz** [comment]
The problem is the version `16.n` of NodeJS you're using.

I apologize for thoughtlessly copying the information about version `14.n` in the package.json file and not verifying if it was correct. It isn't, and the minimum required version is `18.n`.
I usually work with version `20.n`, and it was my mistake not to check this.
I apologize for this oversight.

I am submitting a fix with an update to the required version information.

**Comment by chrisn-au** [comment]
Thx - upgraded to node 18 for the docker container and all is good
